import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
from tqdm import tqdm
from torch.utils.tensorboard import SummaryWriter
from models.vlm import BasicVLM
import torchvision.transforms as transforms
from PIL import Image, ImageDraw, ImageFont
import numpy as np
import io
import cv2
import tempfile
import os
from datetime import datetime
from models.ha_vlm import HaloVLM


# majority of the code is generated by the copilot and deepseek for better logging features into the tensorboard

class BasicVLMTrainer:
    def __init__(self, model, train_loader, val_loader=None, 
                 device='cuda', learning_rate=1e-4, max_epochs=10,
                 log_tensorboard=False, log_dir="./runs"):
        self.model = model.to(device)
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.device = device
        self.max_epochs = max_epochs
        
        # Setup optimizer
        self.optimizer = optim.AdamW(
            self.model.parameters(), 
            lr=learning_rate,
            weight_decay=0.01
        )
        
        # Setup scheduler
        self.scheduler = CosineAnnealingLR(
            self.optimizer, 
            T_max=max_epochs * len(train_loader)
        )
        
        # Loss function - ignore padding tokens
        self.criterion = nn.CrossEntropyLoss(ignore_index=-100)
        
        # Setup logging
        self.log_tensorboard = log_tensorboard
        self.writer = None
        if log_tensorboard:
            self.writer = SummaryWriter(log_dir=log_dir)
        
        self.best_val_loss = float('inf')
        self.global_step = 0
        self.tokenizer = None  # Will be set externally if needed
        
    def set_tokenizer(self, tokenizer):
        """Set tokenizer for decoding predictions"""
        self.tokenizer = tokenizer
    
    def log_gradients(self, step):
        """Log gradient statistics to tensorboard"""
        if not self.log_tensorboard or self.writer is None:
            return
        
        try:
            for name, param in self.model.named_parameters():
                if param.grad is not None:
                    # Log gradient norm
                    grad_norm = param.grad.data.norm(2)
                    self.writer.add_scalar(f'gradients/{name}/norm', grad_norm, step)
                    
                    # Log gradient statistics
                    self.writer.add_scalar(f'gradients/{name}/mean', param.grad.data.mean(), step)
                    self.writer.add_scalar(f'gradients/{name}/std', param.grad.data.std(), step)
                    self.writer.add_scalar(f'gradients/{name}/max', param.grad.data.max(), step)
                    self.writer.add_scalar(f'gradients/{name}/min', param.grad.data.min(), step)
                    
                    # Log gradient histogram
                    self.writer.add_histogram(f'gradients/{name}', param.grad.data, step)
        except Exception as e:
            print(f"Warning: Could not log gradients: {e}")
    
    def log_weight_stats(self, step):
        """Log weight statistics to tensorboard"""
        if not self.log_tensorboard or self.writer is None:
            return
        
        try:
            for name, param in self.model.named_parameters():
                if param.requires_grad:
                    # Log weight norm
                    weight_norm = param.data.norm(2)
                    self.writer.add_scalar(f'weights/{name}/norm', weight_norm, step)
                    
                    # Log weight statistics
                    self.writer.add_scalar(f'weights/{name}/mean', param.data.mean(), step)
                    self.writer.add_scalar(f'weights/{name}/std', param.data.std(), step)
                    
                    # Log weight histogram
                    self.writer.add_histogram(f'weights/{name}', param.data, step)
        except Exception as e:
            print(f"Warning: Could not log weight stats: {e}")
    
    def check_gradients(self):
        """Check for None gradients and print parameters with missing gradients"""
        print("\n" + "="*80)
        print("GRADIENT CHECK REPORT")
        print("="*80)
        
        none_gradient_params = []
        valid_gradient_params = []
        total_params_with_grad = 0
        total_params_without_grad = 0
        none_gradient_param_count = 0
        
        for name, param in self.model.named_parameters():
            total_params = param.numel()
            
            if param.grad is None:
                none_gradient_params.append({
                    'name': name,
                    'shape': tuple(param.shape),
                    'num_params': total_params,
                    'requires_grad': param.requires_grad,
                    'dtype': str(param.dtype)
                })
                if param.requires_grad:
                    none_gradient_param_count += total_params
                total_params_without_grad += total_params
            else:
                valid_gradient_params.append({
                    'name': name,
                    'shape': tuple(param.shape),
                    'num_params': total_params,
                    'grad_norm': param.grad.data.norm(2).item(),
                    'dtype': str(param.dtype)
                })
                total_params_with_grad += total_params
        
        # Print summary
        print(f"\n✓ Parameters WITH gradients: {len(valid_gradient_params)}")
        print(f"  Total parameter count: {total_params_with_grad:,}")
        
        print(f"\n✗ Parameters WITH NONE gradients: {len(none_gradient_params)}")
        print(f"  Total parameter count: {total_params_without_grad:,}")
        print(f"  Parameters with requires_grad=True but grad=None: {none_gradient_param_count:,}")
        
        # Print details of None gradient parameters
        if none_gradient_params:
            print(f"\n{'─'*80}")
            print("DETAILS OF PARAMETERS WITH NONE GRADIENTS:")
            print(f"{'─'*80}")
            print(f"{'Layer Name':<50} {'Shape':<15} {'Num Params':<12} {'Requires Grad':<15}")
            print(f"{'-'*80}")
            
            for param_info in none_gradient_params:
                requires_grad = "✓ Yes" if param_info['requires_grad'] else "✗ No"
                shape_str = str(param_info['shape'])
                print(f"{param_info['name']:<50} {shape_str:<15} {param_info['num_params']:<12,} {requires_grad:<15}")
        
        # Print details of valid gradient parameters (first 10)
        if valid_gradient_params:
            print(f"\n{'─'*80}")
            print("DETAILS OF PARAMETERS WITH VALID GRADIENTS (first 10):")
            print(f"{'─'*80}")
            print(f"{'Layer Name':<50} {'Shape':<15} {'Grad Norm':<15}")
            print(f"{'-'*80}")
            
            for i, param_info in enumerate(valid_gradient_params[:10]):
                shape_str = str(param_info['shape'])
                print(f"{param_info['name']:<50} {shape_str:<15} {param_info['grad_norm']:<15.6e}")
            
            if len(valid_gradient_params) > 10:
                print(f"... and {len(valid_gradient_params) - 10} more parameters with valid gradients")
        
        # Print overall statistics
        print(f"\n{'─'*80}")
        print("OVERALL STATISTICS:")
        print(f"{'─'*80}")
        total_model_params = sum(p.numel() for p in self.model.parameters())
        print(f"Total model parameters: {total_model_params:,}")
        print(f"Parameters with gradients: {total_params_with_grad:,} ({100*total_params_with_grad/total_model_params:.2f}%)")
        print(f"Parameters without gradients: {total_params_without_grad:,} ({100*total_params_without_grad/total_model_params:.2f}%)")
        
        if none_gradient_param_count > 0:
            print(f"\n⚠️  WARNING: {none_gradient_param_count:,} trainable parameters have None gradients!")
            print(f"   This may indicate frozen layers or computational graph issues.")
        else:
            print(f"\n✓ All trainable parameters have valid gradients!")
        
        print("="*80 + "\n")
        
        return {
            'total_params': total_model_params,
            'params_with_grad': total_params_with_grad,
            'params_without_grad': total_params_without_grad,
            'trainable_without_grad': none_gradient_param_count,
            'none_gradient_params': none_gradient_params,
            'valid_gradient_params': valid_gradient_params
        }
    
    def tensor_to_image(self, img_tensor):
        """Convert normalized image tensor to PIL Image"""
        # Handle batch dimension
        if img_tensor.dim() == 4:
            img_tensor = img_tensor[0]
        
        # Denormalize (ImageNet normalization)
        denormalize = transforms.Compose([
            transforms.Normalize(
                mean=[-0.485/0.229, -0.456/0.224, -0.406/0.225],
                std=[1/0.229, 1/0.224, 1/0.225]
            )
        ])
        
        img_tensor = denormalize(img_tensor.cpu())
        img_tensor = torch.clamp(img_tensor, 0, 1)
        img_array = img_tensor.permute(1, 2, 0).numpy()
        img_array = (img_array * 255).astype(np.uint8)
        return Image.fromarray(img_array)
    def visualize_predictions(self, images, input_ids, outputs, texts=None, num_samples=2, num_img_tokens=196, num_question_tokens=4):
        """
        Visualize predicted vs ground truth tokens with MTP support.
        Generates a static image listing the full sequence analysis.
        
        Args:
            outputs: Can be a Dict (logits) or Tensor (token IDs from latent_to_mtp_tokens)
        """
        try:
            from PIL import Image, ImageDraw, ImageFont
            import torch
        except ImportError:
            print("PIL or torch not found.")
            return []

        num_samples = min(num_samples, images.size(0))
        visualizations = []
        
        # Color Palette (Consistent with Video)
        COLORS = {
            'bg': (20, 21, 26),
            'text': (200, 214, 229),
            'correct': (50, 255, 126),
            'incorrect': (255, 71, 87),
            'mtp_future': (255, 165, 2),
            'dim': (100, 100, 100)
        }

        for idx in range(num_samples):
            img_tensor = images[idx:idx+1]
            base_img = self.tensor_to_image(img_tensor).convert("RGB")
            img_width, img_height = base_img.size
            
            # --- 1. ROBUST INPUT HANDLING (From Video Function) ---
            mtp_predictions = None
            main_confidences = None # Only available if inputs are logits
            
            # CASE A: Output is Tensor [B, Seq, Heads] (Inference tokens)
            if isinstance(outputs, torch.Tensor) and outputs.dim() == 3:
                sample_tokens = outputs[idx] # [Seq, Heads]
                main_predictions = sample_tokens[:, 0]
                if sample_tokens.shape[1] > 1:
                    mtp_predictions = sample_tokens[:, 1:] # [Seq, Num_MTP]
            
            # CASE B: Output is Dict (Training logits)
            elif isinstance(outputs, dict):
                main_logits = outputs['main_logits'][idx]
                main_predictions = torch.argmax(main_logits, dim=-1)
                # Calculate confidence for main head
                main_confidences = torch.softmax(main_logits, dim=-1).max(dim=-1)[0]
                
                mtp_logits = outputs.get('mtp_logits', None)
                if mtp_logits is not None:
                    mtp_preds_logits = mtp_logits[idx]
                    mtp_predictions = torch.argmax(mtp_preds_logits, dim=-1)

            # CASE C: Raw Logits Tensor
            else:
                main_logits = outputs[idx]
                main_predictions = torch.argmax(main_logits, dim=-1)
                main_confidences = torch.softmax(main_logits, dim=-1).max(dim=-1)[0]

            # --- 2. DATA PREPARATION ---
            # Slice to text only
            start_pos = min(num_img_tokens, len(main_predictions))
            text_main_preds = main_predictions[start_pos:]
            
            if main_confidences is not None:
                text_confidences = main_confidences[start_pos:]
            else:
                text_confidences = None
                
            if mtp_predictions is not None:
                text_mtp_preds = mtp_predictions[start_pos:]
            else:
                text_mtp_preds = None

            ground_truth = input_ids[idx, 1:] # Shifted GT
            
            # --- 3. SETUP CANVAS ---
            # Determine canvas height based on sequence length
            row_height = 25
            header_height = 80
            list_height = len(text_main_preds) * row_height
            canvas_height = img_height + header_height + list_height + 50
            canvas_width = max(img_width, 1100) # Ensure wide enough for MTP text

            canvas = Image.new('RGB', (canvas_width, canvas_height), color=COLORS['bg'])
            canvas.paste(base_img, (0, 0))
            draw = ImageDraw.Draw(canvas)

            # Fonts
            try:
                font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
                title_font = ImageFont.truetype(font_path, 18)
                text_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 14) # Mono for alignment
            except:
                title_font = ImageFont.load_default()
                text_font = ImageFont.load_default()

            # --- 4. DRAWING ---
            y = img_height + 15
            
            # Calculate Main Accuracy
            valid_len = min(len(text_main_preds), len(ground_truth))
            if valid_len > num_question_tokens:
                matches = (text_main_preds[num_question_tokens:valid_len] == ground_truth[num_question_tokens:valid_len]).sum().item()
                total = valid_len - num_question_tokens
                acc = (matches / total) * 100
            else:
                acc = 0.0

            draw.text((15, y), f"Prediction Analysis | Main Acc: {acc:.1f}%", fill=(255, 255, 255), font=title_font)
            y += 35
            
            # Column Headers
            header_str = f"{'POS':<5} {'GT (TARGET)':<20} {'MAIN PRED':<20} {'MTP FUTURE PEEKS'}"
            draw.text((15, y), header_str, fill=COLORS['text'], font=text_font)
            y += 10
            draw.line([(10, y), (canvas_width-10, y)], fill=COLORS['dim'], width=1)
            y += 15

            # Iterate Tokens
            limit = min(40, len(text_main_preds)) # Don't draw infinite lines
            
            for pos in range(limit):
                # 1. Main Head Logic
                is_question = pos < num_question_tokens
                
                # Get Strings
                gt_str = "---"
                if pos < len(ground_truth):
                    gt_token = ground_truth[pos].item()
                    gt_str = self.tokenizer.decode([gt_token]).replace("Ġ", "").strip() or "␣"
                
                pred_token = text_main_preds[pos].item()
                pred_str = self.tokenizer.decode([pred_token]).replace("Ġ", "").strip() or "␣"
                
                # Check Main Correctness
                is_correct = (pos < len(ground_truth) and gt_token == pred_token)
                main_color = COLORS['correct'] if is_correct else COLORS['incorrect']
                if is_question: main_color = COLORS['dim']
                
                # Format Confidence
                conf_str = ""
                if text_confidences is not None:
                    conf = text_confidences[pos].item()
                    conf_str = f"({conf:.0%})"

                # 2. MTP Logic (Build string)
                mtp_str = ""
                if text_mtp_preds is not None and pos < len(text_mtp_preds):
                    current_futures = text_mtp_preds[pos] # [Num_Heads]
                    futures_list = []
                    
                    for h_idx, token_id in enumerate(current_futures):
                        f_word = self.tokenizer.decode([token_id.item()]).replace("Ġ", "").strip() or "␣"
                        
                        # Check Future Correctness
                        # Head h (offset h+2) targets ground_truth[pos + h + 1]
                        target_idx = pos + h_idx + 1
                        is_fut_correct = False
                        if target_idx < len(ground_truth):
                            if token_id.item() == ground_truth[target_idx].item():
                                is_fut_correct = True
                        
                        # We use a simple unicode mark for correctness in the string
                        mark = "✓" if is_fut_correct else ""
                        futures_list.append(f"+{h_idx+2}:{f_word}{mark}")
                    
                    mtp_str = " | ".join(futures_list)

                # 3. Draw Line
                # We draw piece by piece to handle colors
                x = 15
                
                # Pos
                draw.text((x, y), f"{pos:<5}", fill=COLORS['dim'], font=text_font)
                x += 50 # Adjust based on font size
                
                # GT
                draw.text((x, y), f"{gt_str:<20}", fill=COLORS['dim'], font=text_font)
                x += 180
                
                # Main Pred
                main_display = f"{pred_str} {conf_str}"
                draw.text((x, y), f"{main_display:<20}", fill=main_color, font=text_font)
                x += 180
                
                # MTP
                if mtp_str:
                    draw.text((x, y), f"{mtp_str}", fill=COLORS['mtp_future'], font=text_font)
                
                y += row_height

            visualizations.append(canvas)
            
        return visualizations
    def generate_token_prediction_video(self, images, input_ids, outputs, step=0, fps=2, num_samples=1, num_img_tokens=196, num_question_tokens=4):
        """
        Generate video visualizing predictions using Jump/Flash logic.
        Visualizes blocks of tokens predicted simultaneously by Main + MTP heads.
        """
        try:
            import imageio
            import numpy as np
            from PIL import Image, ImageDraw, ImageFont
            import os
            import torch
        except ImportError:
            print("Warning: libraries not installed. pip install imageio numpy pillow")
            return []

        os.makedirs('./videos', exist_ok=True)
        num_samples = min(num_samples, images.size(0))
        saved_paths = []

        # Enhanced Color Palette from both versions
        COLORS = {
            'overlay_bg': (15, 15, 20, 240), 
            'correct': (50, 255, 126),
            'incorrect': (255, 71, 87),
            'gt_text': (24, 220, 255),
            'header': (140, 150, 170),
            'jump_highlight': (255, 165, 2),  # The "Flash" color
            'label_text': (160, 160, 160),
            'separator': (255, 255, 255, 40)
        }

        try:
            font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" 
            if not os.path.exists(font_path): font_path = "arial.ttf"
            header_font = ImageFont.truetype(font_path, 22)
            text_font = ImageFont.truetype(font_path, 20)
            label_font = ImageFont.truetype(font_path, 12)
        except:
            header_font = text_font = label_font = ImageFont.load_default()

        for sample_idx in range(num_samples):
            try:
                img_tensor = images[sample_idx:sample_idx+1]
                base_img = self.tensor_to_image(img_tensor).convert("RGBA")
                
                # Setup video dimensions
                video_width, video_height = max(base_img.width, 1100), max(base_img.height, 850)
                base_img = base_img.resize((video_width, video_height), Image.Resampling.LANCZOS)

                # --- DATA PARSING ---
                if isinstance(outputs, torch.Tensor):
                    sample_tokens = outputs[sample_idx]
                    main_preds = sample_tokens[:, 0]
                    mtp_preds = sample_tokens[:, 1:] if sample_tokens.shape[1] > 1 else None
                else:
                    main_preds = torch.argmax(outputs['main_logits'][sample_idx], dim=-1)
                    mtp_preds = torch.argmax(outputs['mtp_logits'][sample_idx], dim=-1) if 'mtp_logits' in outputs else None

                # Logic alignment: Identify start of text after image tokens
                start_pos = num_question_tokens # Index in the prediction sequence where we start comparing
                ground_truth = input_ids[sample_idx, 1:] 
                
                # Determine jump size (1 main head + N MTP heads)
                jump_size = 1 + (mtp_preds.shape[1] if mtp_preds is not None else 0)
                
                max_tokens = 24 # Number of tokens to visualize in the video
                frames = []

                # --- PRE-DECODE GT WORDS ---
                gt_words = []
                for tid in ground_truth[:max_tokens + jump_size]:
                    word = self.tokenizer.decode([tid.item()]).replace("Ġ", "").strip() or "␣"
                    gt_words.append(word)

                # --- FRAME GENERATION (JUMP LOGIC) ---
                for current_jump_start in range(0, max_tokens, jump_size):
                    frame = base_img.copy()
                    overlay = Image.new('RGBA', (video_width, video_height), (0,0,0,0))
                    draw = ImageDraw.Draw(overlay)
                    
                    panel_h = 380
                    panel_y = video_height - panel_h
                    draw.rectangle([(0, panel_y), (video_width, video_height)], fill=COLORS['overlay_bg'])
                    
                    margin_x = 45
                    curr_y = panel_y + 40

                    # --- RENDER GROUND TRUTH ---
                    draw.text((margin_x, curr_y), "GROUND TRUTH SEQUENCE", fill=COLORS['header'], font=header_font)
                    curr_y += 40
                    gt_x = margin_x
                    for word in gt_words[:max_tokens]:
                        draw.text((gt_x, curr_y), word, fill=COLORS['gt_text'], font=text_font)
                        gt_x += draw.textbbox((0,0), word, font=text_font)[2] + 12

                    curr_y += 60
                    draw.line([(margin_x, curr_y), (video_width - margin_x, curr_y)], fill=COLORS['separator'], width=1)
                    curr_y += 40

                    # --- RENDER PREDICTIONS (THE FLASH) ---
                    draw.text((margin_x, curr_y), f"MTP PREDICTION (Step {current_jump_start // jump_size + 1})", fill=COLORS['header'], font=header_font)
                    curr_y += 60 
                    line_x = margin_x

                    # Draw tokens predicted so far, including the current "Jump"
                    for i in range(current_jump_start + jump_size):
                        if i >= max_tokens: break
                        
                        # Calculate which block and which head this token belongs to
                        block_idx = (i // jump_size) * jump_size
                        offset = i % jump_size
                        
                        # Map to model output index
                        actual_idx_in_preds = num_img_tokens + block_idx
                        if actual_idx_in_preds >= len(main_preds): break

                        if offset == 0:
                            token_id = main_preds[actual_idx_in_preds].item()
                            head_label = "Head1"
                        else:
                            token_id = mtp_preds[actual_idx_in_preds, offset - 1].item()
                            head_label = f"Head{offset+1}"

                        word = self.tokenizer.decode([token_id]).replace("Ġ", "").strip() or "␣"
                        
                        # Comparison logic
                        gt_comp_idx = block_idx + offset
                        is_correct = (gt_comp_idx < len(ground_truth) and token_id == ground_truth[gt_comp_idx].item())
                        
                        # Color logic: Current jump is Orange, previous are Green/Red
                        if i >= current_jump_start:
                            color = COLORS['jump_highlight']
                        else:
                            color = COLORS['correct'] if is_correct else COLORS['incorrect']

                        # Render Head Label and Word
                        w_width = draw.textbbox((0,0), word, font=text_font)[2]
                        
                        # Label (Head 1, 2...)
                        draw.text((line_x, curr_y - 25), head_label, fill=COLORS['label_text'], font=label_font)
                        # Word
                        draw.text((line_x, curr_y), word, fill=color, font=text_font)
                        
                        line_x += max(w_width, 45) + 15
                        
                        # Simple wrapping
                        if line_x > video_width - 60:
                            line_x = margin_x
                            curr_y += 80

                    final_frame = Image.alpha_composite(frame, overlay)
                    frames.append(np.array(final_frame.convert("RGB")))

                # Save Video
                if frames:
                    video_path = f"./videos/prediction_jump_step{step}_s{sample_idx}.mp4"
                    imageio.mimwrite(video_path, frames, fps=fps, codec='libx264')
                    saved_paths.append(video_path)
                    print(f"✓ Generated Jump Prediction Video: {video_path}")

            except Exception as e:
                print(f"Error in sample {sample_idx}: {e}")
                import traceback; traceback.print_exc()
                
        return saved_paths
    def train_epoch(self, epoch):
        self.model.train()
        total_loss = 0
        total_tokens = 0
        num_batches=0
        
        pbar = tqdm(self.train_loader, desc=f"Epoch {epoch+1}")
        for batch_idx, batch in enumerate(pbar):
        # --------  single batch overfitting code --------
        # single_batch = next(iter(self.train_loader))

        # # Train on this single batch repeatedly
        # pbar = tqdm(range(len(self.train_loader)), desc=f"Epoch {epoch+1}")
        # for batch_idx in pbar:
        #     batch = single_batch
            # Move data to device
            images = batch['images'].to(self.device)
            input_ids = batch['input_ids'].to(self.device)
            attention_mask = batch['attention_mask'].to(self.device)  # ✓ ADD THIS
            labels = batch['labels'].to(self.device)  # ✓ USE LABELS FROM DATALOADER
            
            # Validate that labels are present
            if labels is None:
                raise ValueError("Batch['labels'] is None! Dataloader must provide labels.")
            
            
            # Forward pass
            self.optimizer.zero_grad()
            
            # Get model outputs
            #outputs = self.model(images, input_ids)
            outputs_latent = self.model(images, input_ids, attention_mask=attention_mask)
            
            
            num_img_tokens = 196
            B = input_ids.shape[0]
            seq_len = input_ids.shape[1]  # Original text sequence length
            
            # Create targets with proper shifting
            # instead of ignoring this use this as a self supervision
            image_targets = torch.full((B, num_img_tokens), -100, device=self.device)  # [B, 1]
            text_targets = labels  # [B, seq_len-1] - next tokens for text positions
            
            # Concatenate: [image_targets (ignore) | text_targets (actual predictions)]
            # Final shape: [B, 1 + (seq_len-1)] = [B, seq_len]
            targets = torch.cat([image_targets, text_targets], dim=1)
            # use labels directly without concatenation and shifting as we have already added image token in the beginnning
            #targets = text_targets
            # Model output shape: [B, 1 + seq_len, vocab_size]
            # We only compute loss for first seq_len positions (last position is discarded)
            # outputs_for_loss shape: [B, seq_len, vocab_size]
            # outputs_for_loss = outputs[:, :seq_len, :]
            #outputs_for_loss = outputs[:, :targets.shape[1], :]
            # B. Detach for Gradient Accumulation
            d = outputs_latent.detach()
            d.requires_grad = True
            
            batch_loss = 0.0

            # --- C. Main Head (Standard Prediction) ---
            p_main = self.model.lm_head(d) # [B, 196 + seq_len, Vocab]
            
            # Main head predicts the immediate target at each position
            # We compare p_main directly against targets
            loss_main = self.criterion(
                p_main.reshape(-1, p_main.size(-1)),
                targets.reshape(-1)
            )
            
            loss_main.backward()
            batch_loss += loss_main.item()
            
            # --- D. MTP Heads (Future Predictions) ---
            for i, head in enumerate(self.model.mtp_heads):
                # i=0 -> Head predicts t+2 (relative to input), which is Next Token + 1
                # Since 'targets' already represents the "Next Token", 
                # we need to shift targets by (i + 1) to get the future.
                offset = i + 1 
                
                # Stop if offset exceeds sequence length
                if offset >= targets.shape[1]:
                    print("breaking because of the size issue")
                    break
                    
                p_aux = head(d) # [B, 196 + seq_len, Vocab]
                
                # SLICING LOGIC:
                # Prediction at pos 't' should match Target at pos 't + offset'
                # Valid predictions: [0 : end - offset]
                # Valid targets:     [offset : end]
                
                curr_logits = p_aux[:, :-offset, :]
                curr_targets = targets[:, offset:]
                
                loss_aux = self.criterion(
                    curr_logits.reshape(-1, curr_logits.size(-1)),
                    curr_targets.reshape(-1)
                )
                
                loss_aux.backward()
                batch_loss += loss_aux.item()

            # --- E. Backbone Backward ---
            # Push accumulated gradients from d.grad back into the frozen backbone
            outputs_latent.backward(d.grad)



            # Check gradients on first batch of first epoch
            if epoch == 0 and batch_idx == 0:
                print("\nChecking gradients after first backward pass...")
                self.check_gradients()
            
            # Gradient clipping
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)
            
            # Optimizer step
            self.optimizer.step()
            self.scheduler.step()
            
            # Calculate token-level loss for logging
            batch_tokens = (targets != -100).sum().item()
            #batch_loss = loss.item() * batch_tokens
            
            total_loss += batch_loss
            num_batches+=1

            
            # Update progress bar
            avg_loss = total_loss / num_batches
            pbar.set_postfix({
                'loss': f'{avg_loss:.4f}',
                'lr': f'{self.scheduler.get_last_lr()[0]:.6f}'
            })
            
            # Log to tensorboard
            if self.log_tensorboard and batch_idx % 1000 == 0:
                self.writer.add_scalar('train_loss_step main head', loss_main.item(), self.global_step)
                self.writer.add_scalar('learning_rate', self.scheduler.get_last_lr()[0], self.global_step)
                
                # Log gradient statistics
                self.log_gradients(self.global_step)
                self.log_weight_stats(self.global_step)
                
                #Log image predictions visualization (every 1000 steps)
                try:
                    texts = batch.get('texts', None)
                    # Use original outputs (before slicing) for visualization
                    pred_images = self.visualize_predictions(
                        images, input_ids, self.latent_to_mtp_tokens(self.model(images, input_ids,attention_mask)), 
                        texts=texts, num_samples=2
                    )
                    for i, pred_img in enumerate(pred_images):
                        self.writer.add_image(
                            f'train_predictions_sample_{i}',
                            np.array(pred_img),
                            self.global_step,
                            dataformats='HWC'
                        )
                except Exception as e:
                    print(f"Warning: Could not log prediction images: {e}")
                
                # # Generate and save prediction videos
                # if self.global_step % 10 == 0:
                # Generate and save prediction videos
                # if self.global_step % 10 == 0:
                try:
                    # --- FIX: OPTIMIZED INFERENCE ---
                    
                    # 1. Slice inputs first! 
                    # Only process 1 sample instead of the full batch (e.g. 32).
                    # This reduces memory usage by ~95%.
                    img_viz = images[:1]
                    ids_viz = input_ids[:1]
                    mask_viz = attention_mask[:1]
                    
                    # 2. Disable Gradients
                    # Prevents storing activations for backprop (saves 50%+ VRAM).
                    with torch.no_grad():
                        # Run model ONLY on the single sample
                        outputs_viz = self.model(img_viz, ids_viz, attention_mask=mask_viz)
                        tokens_viz = self.latent_to_mtp_tokens(outputs_viz)
                    
                    # 3. Generate Video
                    # Pass the sliced, detached tensors
                    video_paths = self.generate_token_prediction_video(
                        img_viz, ids_viz, tokens_viz,
                        step=batch_idx, fps=2, num_samples=1
                    )
                    
                    if video_paths:
                        print(f"✓ Saved {len(video_paths)} token prediction video(s)")
                except Exception as e:
                    print(f"Warning: Could not generate videos: {e}")
                # self.global_step += 1
        
        return total_loss / num_batches
    
    def validate(self, epoch=0):
        if self.val_loader is None:
            return None

        self.model.eval()
        total_loss = 0
        total_tokens = 0

        pbar = tqdm(self.val_loader, desc="Validation")
        for batch_idx, batch in enumerate(pbar):
            images = batch['images'].to(self.device)
            input_ids = batch['input_ids'].to(self.device)
            attention_mask = batch['attention_mask'].to(self.device)
            labels = batch['labels'].to(self.device)

            # Forward pass
            with torch.no_grad():
                outputs = self.model(images, input_ids, attention_mask=attention_mask)

            # Prepare targets (same as training)
            num_img_tokens = 196
            B = input_ids.shape[0]
            
            # Create targets with proper shifting
            image_targets = torch.full((B, num_img_tokens), -100, device=self.device)
            text_targets = labels  # Already shifted labels from dataloader
            
            # Concatenate: [image_targets (ignore) | text_targets (actual predictions)]
            targets = torch.cat([image_targets, text_targets], dim=1)
            
            # Slice outputs to match target length
            outputs_for_loss = outputs[:, :targets.shape[1], :]
            
            # Validate shapes
            assert outputs_for_loss.shape[0] == targets.shape[0], f"Batch size mismatch: {outputs_for_loss.shape[0]} vs {targets.shape[0]}"
            assert outputs_for_loss.shape[1] == targets.shape[1], f"Sequence length mismatch: {outputs_for_loss.shape[1]} vs {targets.shape[1]}"

            # Calculate loss
            loss = self.criterion(
                outputs_for_loss.reshape(-1, outputs_for_loss.size(-1)),
                targets.reshape(-1)
            )

            # Calculate token-level loss
            batch_tokens = (targets != -100).sum().item()
            batch_loss = loss.item() * batch_tokens
            
            total_loss += batch_loss
            total_tokens += batch_tokens

            # Update progress bar with average loss
            avg_loss = total_loss / max(total_tokens, 1)
            pbar.set_postfix({'val_loss': f'{avg_loss:.4f}'})

            # Log validation predictions on first batch
            if self.log_tensorboard and batch_idx == 0:
                try:
                    texts = batch.get('texts', None)
                    pred_images = self.visualize_predictions(
                        images, input_ids, outputs, 
                        texts=texts, num_samples=2
                    )
                    for i, pred_img in enumerate(pred_images):
                        self.writer.add_image(
                            f'val_predictions_sample_{i}',
                            np.array(pred_img),
                            epoch,
                            dataformats='HWC'
                        )
                    
                    # Generate validation video
                    video_paths = self.generate_token_prediction_video(
                        images, input_ids, outputs,
                        step=epoch, fps=2, num_samples=1, num_img_tokens=196
                    )
                    if video_paths:
                        print(f"✓ Saved {len(video_paths)} validation video(s)")
                        
                except Exception as e:
                    print(f"Warning: Could not log validation prediction images: {e}")

        avg_loss = total_loss / max(total_tokens, 1)
        
        # Log validation loss to tensorboard
        if self.log_tensorboard:
            self.writer.add_scalar('val_loss_epoch', avg_loss, epoch)
        
        return avg_loss

    
    def train(self):
        print(f"Starting training for {self.max_epochs} epochs")
        print(f"Training samples: {len(self.train_loader.dataset)}")
        if self.val_loader:
            print(f"Validation samples: {len(self.val_loader.dataset)}")
        
        for epoch in range(self.max_epochs):
            # Train
            train_loss = self.train_epoch(epoch)
            
            # Validate
            val_loss = self.validate(epoch=epoch)
            
            # Log epoch results
            print(f"\nEpoch {epoch+1}/{self.max_epochs}")
            print(f"Train Loss: {train_loss:.4f}")
            if val_loss is not None:
                print(f"Val Loss: {val_loss:.4f}")
                
                # Save best model
                if val_loss < self.best_val_loss:
                    self.best_val_loss = val_loss
                    self.save_checkpoint(f'best_model_epoch_{epoch+1}.pt')
                    print(f"Saved best model with val loss: {val_loss:.4f}")
            
            # Save checkpoint
            self.save_checkpoint(f'checkpoint_epoch_{epoch+1}.pt')
            
            # Log to tensorboard
            if self.log_tensorboard:
                self.writer.add_scalar('epoch_train_loss', train_loss, epoch+1)
                if val_loss is not None:
                    self.writer.add_scalar('epoch_val_loss', val_loss, epoch+1)
        
        print("Training completed!")
        if self.log_tensorboard and self.writer is not None:
            self.writer.close()
    
    def save_checkpoint(self, path):
        checkpoint = {
            'model_state_dict': self.model.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
            'scheduler_state_dict': self.scheduler.state_dict(),
            'epoch': self.max_epochs,
            'best_val_loss': self.best_val_loss,
            'model_config': {
                'vocab_size': self.model.token_embeds.num_embeddings,
                'embed_dim': self.model.token_embeds.embedding_dim
            }
        }
        torch.save(checkpoint, path)
        print(f"Checkpoint saved to {path}")
    
    def load_checkpoint(self, path):
        checkpoint = torch.load(path, map_location=self.device)
        self.model.load_state_dict(checkpoint['model_state_dict'])
        self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        self.scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
        self.best_val_loss = checkpoint['best_val_loss']
        print(f"Checkpoint loaded from {path}")

    def latent_to_mtp_tokens(self, d):
        """
        Converts latent representations `d` into predicted tokens from
        the Main Head and all MTP heads.
        
        Logic:
        - Main Head output at pos t corresponds to token t+1.
        - MTP Head[i] output at pos t corresponds to token t+(i+2).
        
        Args:
            d: Latent representation tensor. 
               Shape: [B, Seq_Len, Hidden_Size] (full sequence)
               OR [B, 1, Hidden_Size] (current step for generation)
            
        Returns:
            torch.Tensor: Stacked predictions of shape [B, Seq_Len, 1 + Num_MTP_Heads].
                          The last dim contains [Main_Pred, MTP_1, MTP_2, ...].
        """
        # Ensure we don't track gradients for inference-style decoding
        with torch.no_grad():
            preds_list = []
            
            # --- 1. Main Head (Predicts Immediate Next Token) ---
            # d -> lm_head -> logits -> argmax
            logits_main = self.model.lm_head(d)  # [B, S, Vocab]
            tokens_main = torch.argmax(logits_main, dim=-1)  # [B, S]
            preds_list.append(tokens_main)
            
            # --- 2. MTP Heads (Predict Future Tokens) ---
            # Iterate through heads in order (Head 0 -> t+2, Head 1 -> t+3, etc.)
            for head in self.model.mtp_heads:
                logits_aux = head(d)  # [B, S, Vocab]
                tokens_aux = torch.argmax(logits_aux, dim=-1)  # [B, S]
                preds_list.append(tokens_aux)
            
            # --- 3. Stack Results ---
            # Stack along a new dimension to group predictions by timestep
            # Final Shape: [B, Seq_Len, Num_Heads_Total]
            all_tokens = torch.stack(preds_list, dim=-1)
            
            return all_tokens



if __name__ == "__main__":
    
    # Use the same tokenizer as in your data loader
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
    vocab_size = tokenizer.vocab_size
    
    model = HaloVLM(
        vocab_size=vocab_size,
        emb_dim=512
    )
    
    # Get dataloaders (from your existing code)
    from lavis.datasets.builders import load_dataset
    import os
    
    os.environ['cache_root'] = "/home/ha/.cache/lavis/coco"
    
    coco_dataset = load_dataset("coco_caption")
    
    from dataloader import create_vlm_dataloaders
    
    print("\nCreating dataloaders...")
    dataloaders = create_vlm_dataloaders(
        coco_dataset,
        batch_size=8,
        num_workers=4,
        tokenizer=tokenizer,
        max_length=17
    )
    
    train_loader = dataloaders['train']
    val_loader = dataloaders.get('val', None)
    
    # Create trainer
    trainer = BasicVLMTrainer(
        model=model,
        train_loader=train_loader,
        val_loader=val_loader,
        device='cuda' if torch.cuda.is_available() else 'cpu',
        learning_rate=3e-4,
        max_epochs=500,
        log_tensorboard=True,  # Set to True if you want tensorboard logging
        log_dir="./runs/vlm_training"
    )
    
    # Set tokenizer for prediction visualization
    trainer.set_tokenizer(tokenizer)
    
    # Start training
    trainer.train()

